# This workflow will apply a label to an issue when it is closed.
# For more information, see:
# https://github.com/KeisukeYamashita/attach-labels

name: Add Labels
on:
  issues:
    types: [closed]
#   pull_request_review:
#     types: [submitted]

jobs:
  add-unvalidated-label:
    name: Add Unvalidated Label
    runs-on: ubuntu-latest
    steps:
      - uses: KeisukeYamashita/attach-labels@v1
        if: github.event_name == 'issues' && ( contains(github.event.issue.title, 'Bug') || contains(github.event.issue.title, 'BUG') || contains(github.event.issue.title, 'bug') )
        with:
          labels: unvalidated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
