# This workflow will apply a label to an issue when it is closed.
# For more information, see:
# https://github.com/KeisukeYamashita/attach-labels

name: Add Labels
on:
  issues:
    types: [closed]
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted]

jobs:
  add_validated_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        if: github.event_name == 'issue_comment' && (contains(github.event.comment.body, 'Validated') || contains(github.event.comment.body, 'validated'))
        with:
          labels: validated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  add_unvalidated_label:
    name: Add Unvalidated Label
    runs-on: ubuntu-latest
    steps:
      - uses: KeisukeYamashita/attach-labels@v1
        if: github.event_name == 'issues' && !contains(github.event.issue.labels, 'validated')
        with:
          labels: unvalidated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  add_changes_requested_label:
    name: Add Changes Requested Label
    runs-on: ubuntu-latest
    steps:
      - uses: KeisukeYamashita/attach-labels@v1
        if: github.event_name == 'pull_request_review' && github.event.review.state == 'changes_requested'
        with:
          labels: changes-requested
#           number: github.event.pull_request.number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
